import type { ComponentItem, StyleItem } from '@/types/catalog'
import type { MotionParams } from '@/lib/motion/presets'

/**
 * Phase 2 (Frontend Code Direct Output): turn the current style tokens /
 * component preview / motion parameters into standalone, paste-ready code
 * strings. Everything here is pure string generation — no runtime coupling
 * with the preview implementation.
 */

type Tokens = Record<string, string>

/** Ordered, human-friendly listing of the `--sc-*` token keys we emit. */
const TOKEN_ORDER = [
  '--sc-bg',
  '--sc-bg-fallback',
  '--sc-fg',
  '--sc-primary',
  '--sc-primary-fg',
  '--sc-muted',
  '--sc-muted-fg',
  '--sc-border',
  '--sc-radius',
  '--sc-shadow',
  '--sc-font',
  '--sc-backdrop',
]

function orderedEntries(tokens: Tokens): [string, string][] {
  const known = TOKEN_ORDER.filter((k) => tokens[k] != null).map((k) => [k, tokens[k]] as [string, string])
  const rest = Object.entries(tokens)
    .filter(([k]) => !TOKEN_ORDER.includes(k))
    .sort(([a], [b]) => a.localeCompare(b))
  return [...known, ...rest]
}

/* ------------------------------------------------------------------ */
/* Token export                                                        */
/* ------------------------------------------------------------------ */

export function tokensToCssVars(tokens: Tokens, styleName?: string): string {
  const lines = orderedEntries(tokens).map(([k, v]) => `  ${k}: ${v};`)
  return [
    `/* Design tokens${styleName ? ` — "${styleName}"` : ''} · generated by Prompt Assistant */`,
    ':root {',
    ...lines,
    '}',
    '',
    '/* Usage: background: var(--sc-bg); color: var(--sc-fg); etc. */',
  ].join('\n')
}

/** Bare `:root { ... }` block, no header/usage comments — meant for embedding elsewhere (e.g. prompts). */
function tokensToCssVarsBlock(tokens: Tokens): string {
  const lines = orderedEntries(tokens).map(([k, v]) => `  ${k}: ${v};`)
  return [':root {', ...lines, '}'].join('\n')
}

/**
 * Appends a ready-to-paste CSS variables block to a style's prompt text, so
 * that copying the prompt into any AI/dev tool carries exact color/token
 * values alongside the free-text description — not just a verbal summary
 * that's open to interpretation. Applied once to all bundled styles at
 * catalog build time (see `generateAllStyles()`); left untouched for
 * user-imported styles so we never double-append.
 */
export function appendCodeSampleToPrompt(style: StyleItem): StyleItem {
  const cssBlock = tokensToCssVarsBlock(style.tokens)
  return {
    ...style,
    prompt: {
      'zh-CN': `${style.prompt['zh-CN']}\n\n对应 CSS 变量（可直接使用，确保生成结果的配色/圆角/字体与设计完全一致）：\n\`\`\`css\n${cssBlock}\n\`\`\``,
      'en-US': `${style.prompt['en-US']}\n\nCorresponding CSS variables (use directly to keep colors/radius/font exactly on-spec):\n\`\`\`css\n${cssBlock}\n\`\`\``,
    },
  }
}

export function tokensToTailwindConfig(tokens: Tokens, styleName?: string): string {
  const fontStack = (tokens['--sc-font'] ?? 'Inter, system-ui, sans-serif')
    .split(',')
    .map((f) => `'${f.trim().replace(/^['"]|['"]$/g, '')}'`)
    .join(', ')
  return `// tailwind.config.js — theme.extend${styleName ? ` for "${styleName}"` : ''} · generated by Prompt Assistant
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        background: '${tokens['--sc-bg-fallback'] ?? tokens['--sc-bg'] ?? '#0f172a'}',
        foreground: '${tokens['--sc-fg'] ?? '#f8fafc'}',
        primary: {
          DEFAULT: '${tokens['--sc-primary'] ?? '#6366f1'}',
          foreground: '${tokens['--sc-primary-fg'] ?? '#ffffff'}',
        },
        muted: {
          DEFAULT: '${tokens['--sc-muted'] ?? '#1e293b'}',
          foreground: '${tokens['--sc-muted-fg'] ?? '#94a3b8'}',
        },
        border: '${tokens['--sc-border'] ?? '#334155'}',
      },
      borderRadius: {
        theme: '${tokens['--sc-radius'] ?? '8px'}',
      },
      boxShadow: {
        theme: '${tokens['--sc-shadow'] ?? '0 4px 12px rgba(0,0,0,0.3)'}',
      },
      fontFamily: {
        theme: [${fontStack}],
      },
    },
  },
}`
}

/* ------------------------------------------------------------------ */
/* Motion export                                                       */
/* ------------------------------------------------------------------ */

export function motionParamsToCode(p: MotionParams): string {
  return `// Motion parameters · generated by Prompt Assistant (npm i motion)
import { motion } from 'motion/react'

export const spring = {
  type: 'spring',
  stiffness: ${p.stiffness},
  damping: ${p.damping},
  mass: ${p.mass},
} as const

export const enter = { duration: ${p.enterDuration}, delay: ${p.enterDelay}, ease: [0.22, 1, 0.36, 1] } as const

export const hover = { scale: ${p.hoverScale}, y: ${p.hoverLift} } as const
export const press = { scale: ${p.pressScale} } as const

/* Usage:
  <motion.button whileHover={hover} whileTap={press} transition={spring}>…</motion.button>
  <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={enter}>…</motion.div>
*/`
}

/* ------------------------------------------------------------------ */
/* Component code export                                               */
/* ------------------------------------------------------------------ */

interface T {
  bg: string
  fg: string
  primary: string
  primaryFg: string
  muted: string
  mutedFg: string
  border: string
  radius: string
  shadow: string
  font: string
  backdrop?: string
}

function pickTokens(tokens: Tokens): T {
  const bg = tokens['--sc-bg'] ?? '#0f172a'
  return {
    bg,
    fg: tokens['--sc-fg'] ?? '#f8fafc',
    primary: tokens['--sc-primary'] ?? '#6366f1',
    primaryFg: tokens['--sc-primary-fg'] ?? '#ffffff',
    muted: tokens['--sc-muted'] ?? '#1e293b',
    mutedFg: tokens['--sc-muted-fg'] ?? '#94a3b8',
    border: tokens['--sc-border'] ?? '#334155',
    radius: tokens['--sc-radius'] ?? '8px',
    shadow: tokens['--sc-shadow'] ?? '0 4px 12px rgba(0,0,0,0.3)',
    font: tokens['--sc-font'] ?? 'Inter, system-ui, sans-serif',
    backdrop: tokens['--sc-backdrop'],
  }
}

function tokensConst(t: T): string {
  const lines = [
    `  bg: '${t.bg}',`,
    `  fg: '${t.fg}',`,
    `  primary: '${t.primary}',`,
    `  primaryFg: '${t.primaryFg}',`,
    `  muted: '${t.muted}',`,
    `  mutedFg: '${t.mutedFg}',`,
    `  border: '${t.border}',`,
    `  radius: '${t.radius}',`,
    `  shadow: '${t.shadow}',`,
    `  font: '${t.font}',`,
  ]
  if (t.backdrop) lines.push(`  backdrop: '${t.backdrop}',`)
  return `const T = {\n${lines.join('\n')}\n} as const`
}

function pascalCase(id: string): string {
  return id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('')
}

/**
 * Per-component JSX bodies for the most used components. Each returns the
 * exported function's source; `T` (tokens const) is always in scope.
 */
const COMPONENT_TEMPLATES: Record<string, (name: string) => string> = {
  buttons: (name) => `export function ${name}() {
  const base: React.CSSProperties = {
    padding: '8px 16px',
    borderRadius: T.radius,
    fontFamily: T.font,
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  }
  return (
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
      <button style={{ ...base, background: T.primary, color: T.primaryFg, border: \`1px solid \${T.border}\` }}>Primary</button>
      <button style={{ ...base, background: T.muted, color: T.fg, border: \`1px solid \${T.border}\` }}>Secondary</button>
      <button style={{ ...base, background: 'transparent', color: T.fg, border: \`1px solid \${T.border}\` }}>Outline</button>
      <button style={{ ...base, background: 'transparent', color: T.mutedFg, border: '1px solid transparent' }}>Ghost</button>
    </div>
  )
}`,

  'content-card': (name) => `export function ${name}() {
  return (
    <div
      style={{
        maxWidth: 360,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: 20,
        fontFamily: T.font,
      }}
    >
      <h3 style={{ margin: '0 0 8px', color: T.fg, fontSize: 17, fontWeight: 600 }}>Card title</h3>
      <p style={{ margin: '0 0 16px', color: T.mutedFg, fontSize: 13, lineHeight: 1.6 }}>
        Supporting copy that explains what this card is about.
      </p>
      <button
        style={{
          padding: '7px 14px',
          background: T.primary,
          color: T.primaryFg,
          border: 'none',
          borderRadius: T.radius,
          fontFamily: T.font,
          fontSize: 13,
          fontWeight: 600,
          cursor: 'pointer',
        }}
      >
        Learn more
      </button>
    </div>
  )
}`,

  badges: (name) => `export function ${name}() {
  const badge = (bg: string, fg: string, label: string, outlined = false): React.ReactNode => (
    <span
      style={{
        padding: '3px 10px',
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 600,
        fontFamily: T.font,
        background: outlined ? 'transparent' : bg,
        color: fg,
        border: outlined ? \`1px solid \${T.border}\` : 'none',
      }}
    >
      {label}
    </span>
  )
  return (
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
      {badge(T.primary, T.primaryFg, 'New')}
      {badge(T.muted, T.fg, 'Default')}
      {badge('transparent', T.mutedFg, 'Outline', true)}
    </div>
  )
}`,

  'text-input': (name) => `export function ${name}() {
  return (
    <label style={{ display: 'block', maxWidth: 320, fontFamily: T.font }}>
      <span style={{ display: 'block', marginBottom: 6, color: T.fg, fontSize: 13, fontWeight: 600 }}>Email</span>
      <input
        type="email"
        placeholder="you@example.com"
        style={{
          width: '100%',
          padding: '9px 12px',
          background: T.muted,
          color: T.fg,
          border: \`1px solid \${T.border}\`,
          borderRadius: T.radius,
          fontFamily: T.font,
          fontSize: 14,
          outline: 'none',
          boxSizing: 'border-box',
        }}
      />
      <span style={{ display: 'block', marginTop: 6, color: T.mutedFg, fontSize: 12 }}>We never share your email.</span>
    </label>
  )
}`,

  'search-input': (name) => `export function ${name}() {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        maxWidth: 320,
        padding: '8px 12px',
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        fontFamily: T.font,
      }}
    >
      <span style={{ color: T.mutedFg, fontSize: 14 }}>⌕</span>
      <input
        type="search"
        placeholder="Search…"
        style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: T.fg, fontSize: 14, fontFamily: T.font }}
      />
      <kbd style={{ color: T.mutedFg, fontSize: 11, border: \`1px solid \${T.border}\`, borderRadius: 4, padding: '1px 5px' }}>/</kbd>
    </div>
  )
}`,

  'toggle-switch': (name) => `import { useState } from 'react'

export function ${name}() {
  const [on, setOn] = useState(true)
  return (
    <button
      type="button"
      role="switch"
      aria-checked={on}
      onClick={() => setOn(!on)}
      style={{
        position: 'relative',
        width: 44,
        height: 24,
        borderRadius: 999,
        border: \`1px solid \${T.border}\`,
        background: on ? T.primary : T.muted,
        cursor: 'pointer',
        transition: 'background 0.2s ease',
        padding: 0,
      }}
    >
      <span
        style={{
          position: 'absolute',
          top: 2,
          left: on ? 22 : 2,
          width: 18,
          height: 18,
          borderRadius: 999,
          background: on ? T.primaryFg : T.mutedFg,
          transition: 'left 0.2s ease',
        }}
      />
    </button>
  )
}`,

  'modal-dialog': (name) => `export function ${name}({ onCancel, onConfirm }: { onCancel?: () => void; onConfirm?: () => void }) {
  return (
    <div
      role="dialog"
      aria-modal="true"
      style={{
        maxWidth: 400,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: 20,
        fontFamily: T.font,
      }}
    >
      <h3 style={{ margin: '0 0 8px', color: T.fg, fontSize: 17, fontWeight: 600 }}>Confirm action</h3>
      <p style={{ margin: '0 0 16px', color: T.mutedFg, fontSize: 13 }}>This action cannot be undone.</p>
      <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
        <button
          onClick={onCancel}
          style={{
            padding: '7px 14px',
            border: \`1px solid \${T.border}\`,
            background: 'transparent',
            color: T.fg,
            borderRadius: T.radius,
            fontFamily: T.font,
            fontSize: 13,
            cursor: 'pointer',
          }}
        >
          Cancel
        </button>
        <button
          onClick={onConfirm}
          style={{
            padding: '7px 14px',
            border: 'none',
            background: T.primary,
            color: T.primaryFg,
            borderRadius: T.radius,
            fontFamily: T.font,
            fontSize: 13,
            fontWeight: 600,
            cursor: 'pointer',
          }}
        >
          Confirm
        </button>
      </div>
    </div>
  )
}`,

  'toast-notifications': (name) => `export function ${name}({ title = 'Saved', body = 'Your changes have been saved.' }: { title?: string; body?: string }) {
  return (
    <div
      role="status"
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 10,
        maxWidth: 360,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderLeft: \`3px solid \${T.primary}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: '10px 12px',
        fontFamily: T.font,
      }}
    >
      <span style={{ width: 8, height: 8, marginTop: 5, borderRadius: 999, background: T.primary, flexShrink: 0 }} />
      <div>
        <div style={{ color: T.fg, fontSize: 13, fontWeight: 600 }}>{title}</div>
        <div style={{ color: T.mutedFg, fontSize: 12 }}>{body}</div>
      </div>
    </div>
  )
}`,

  'alert-banner': (name) => `export function ${name}({ message = 'A new version is available.' }: { message?: string }) {
  return (
    <div
      role="alert"
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '10px 14px',
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        fontFamily: T.font,
      }}
    >
      <span style={{ width: 8, height: 8, borderRadius: 999, background: T.primary, flexShrink: 0 }} />
      <p style={{ margin: 0, flex: 1, color: T.fg, fontSize: 13 }}>{message}</p>
      <button
        style={{ background: 'transparent', border: 'none', color: T.mutedFg, cursor: 'pointer', fontSize: 14, fontFamily: T.font }}
        aria-label="Dismiss"
      >
        ✕
      </button>
    </div>
  )
}`,

  'progress-bar': (name) => `export function ${name}({ value = 64 }: { value?: number }) {
  return (
    <div style={{ maxWidth: 320, fontFamily: T.font }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
        <span style={{ color: T.fg, fontSize: 13, fontWeight: 600 }}>Uploading…</span>
        <span style={{ color: T.mutedFg, fontSize: 12 }}>{value}%</span>
      </div>
      <div
        role="progressbar"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={100}
        style={{ height: 8, background: T.muted, border: \`1px solid \${T.border}\`, borderRadius: 999, overflow: 'hidden' }}
      >
        <div style={{ width: \`\${value}%\`, height: '100%', background: T.primary, borderRadius: 999, transition: 'width 0.3s ease' }} />
      </div>
    </div>
  )
}`,

  'stat-card': (name) => `export function ${name}({ label = 'Monthly revenue', value = '$48,210', delta = '+12.4%' }: { label?: string; value?: string; delta?: string }) {
  return (
    <div
      style={{
        maxWidth: 240,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: 16,
        fontFamily: T.font,
      }}
    >
      <p style={{ margin: '0 0 4px', color: T.mutedFg, fontSize: 12 }}>{label}</p>
      <p style={{ margin: '0 0 6px', color: T.fg, fontSize: 24, fontWeight: 700 }}>{value}</p>
      <span
        style={{
          display: 'inline-block',
          padding: '2px 8px',
          borderRadius: 999,
          background: T.primary,
          color: T.primaryFg,
          fontSize: 11,
          fontWeight: 600,
        }}
      >
        {delta}
      </span>
    </div>
  )
}`,

  navbar: (name) => `export function ${name}() {
  const link = (label: string, active = false): React.ReactNode => (
    <a
      href="#"
      style={{
        padding: '6px 12px',
        borderRadius: T.radius,
        color: active ? T.primaryFg : T.mutedFg,
        background: active ? T.primary : 'transparent',
        fontSize: 13,
        fontWeight: active ? 600 : 500,
        textDecoration: 'none',
      }}
    >
      {label}
    </a>
  )
  return (
    <nav
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '10px 16px',
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        fontFamily: T.font,
      }}
    >
      <strong style={{ color: T.fg, fontSize: 15 }}>Brand</strong>
      <div style={{ display: 'flex', gap: 4 }}>
        {link('Home', true)}
        {link('Products')}
        {link('Pricing')}
        {link('About')}
      </div>
    </nav>
  )
}`,

  'sign-in-form': (name) => `import { useState } from 'react'

export function ${name}() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const field: React.CSSProperties = {
    width: '100%',
    padding: '9px 12px',
    background: T.muted,
    color: T.fg,
    border: \`1px solid \${T.border}\`,
    borderRadius: T.radius,
    fontFamily: T.font,
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
  }
  return (
    <form
      onSubmit={(e) => e.preventDefault()}
      style={{
        maxWidth: 340,
        display: 'flex',
        flexDirection: 'column',
        gap: 12,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: 24,
        fontFamily: T.font,
      }}
    >
      <h2 style={{ margin: 0, color: T.fg, fontSize: 18, fontWeight: 700 }}>Sign in</h2>
      <input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} style={field} />
      <input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} style={field} />
      <button
        type="submit"
        style={{
          padding: '10px 14px',
          background: T.primary,
          color: T.primaryFg,
          border: 'none',
          borderRadius: T.radius,
          fontFamily: T.font,
          fontSize: 14,
          fontWeight: 600,
          cursor: 'pointer',
        }}
      >
        Continue
      </button>
      <a href="#" style={{ color: T.mutedFg, fontSize: 12, textAlign: 'center', textDecoration: 'none' }}>
        Forgot password?
      </a>
    </form>
  )
}`,

  'table-basic': (name) => `export function ${name}() {
  const rows = [
    { name: 'Aurora Chen', role: 'Designer', status: 'Active' },
    { name: 'Liam Park', role: 'Engineer', status: 'Away' },
    { name: 'Maya Ortiz', role: 'PM', status: 'Active' },
  ]
  const cell: React.CSSProperties = { padding: '10px 14px', fontSize: 13, textAlign: 'left' }
  return (
    <table
      style={{
        width: '100%',
        maxWidth: 520,
        borderCollapse: 'collapse',
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        overflow: 'hidden',
        fontFamily: T.font,
      }}
    >
      <thead>
        <tr style={{ borderBottom: \`1px solid \${T.border}\` }}>
          <th style={{ ...cell, color: T.mutedFg, fontWeight: 600 }}>Name</th>
          <th style={{ ...cell, color: T.mutedFg, fontWeight: 600 }}>Role</th>
          <th style={{ ...cell, color: T.mutedFg, fontWeight: 600 }}>Status</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((r) => (
          <tr key={r.name} style={{ borderBottom: \`1px solid \${T.border}\` }}>
            <td style={{ ...cell, color: T.fg, fontWeight: 500 }}>{r.name}</td>
            <td style={{ ...cell, color: T.mutedFg }}>{r.role}</td>
            <td style={cell}>
              <span
                style={{
                  padding: '2px 8px',
                  borderRadius: 999,
                  fontSize: 11,
                  fontWeight: 600,
                  background: r.status === 'Active' ? T.primary : T.muted,
                  color: r.status === 'Active' ? T.primaryFg : T.mutedFg,
                  border: r.status === 'Active' ? 'none' : \`1px solid \${T.border}\`,
                }}
              >
                {r.status}
              </span>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}`,

  tabs: (name) => `import { useState } from 'react'

export function ${name}() {
  const tabs = ['Overview', 'Analytics', 'Settings']
  const [active, setActive] = useState(0)
  return (
    <div style={{ maxWidth: 420, fontFamily: T.font }}>
      <div style={{ display: 'flex', gap: 4, borderBottom: \`1px solid \${T.border}\` }}>
        {tabs.map((tab, i) => (
          <button
            key={tab}
            onClick={() => setActive(i)}
            style={{
              padding: '8px 14px',
              background: 'transparent',
              border: 'none',
              borderBottom: i === active ? \`2px solid \${T.primary}\` : '2px solid transparent',
              color: i === active ? T.fg : T.mutedFg,
              fontSize: 13,
              fontWeight: i === active ? 600 : 500,
              cursor: 'pointer',
              fontFamily: T.font,
            }}
          >
            {tab}
          </button>
        ))}
      </div>
      <p style={{ padding: '14px 2px', color: T.mutedFg, fontSize: 13 }}>Content for “{tabs[active]}”.</p>
    </div>
  )
}`,

  pagination: (name) => `import { useState } from 'react'

export function ${name}({ totalPages = 5 }: { totalPages?: number }) {
  const [page, setPage] = useState(1)
  const btn = (active: boolean): React.CSSProperties => ({
    minWidth: 32,
    height: 32,
    borderRadius: T.radius,
    border: \`1px solid \${active ? T.primary : T.border}\`,
    background: active ? T.primary : 'transparent',
    color: active ? T.primaryFg : T.fg,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: T.font,
  })
  return (
    <nav style={{ display: 'flex', gap: 6, alignItems: 'center', fontFamily: T.font }}>
      <button style={btn(false)} disabled={page === 1} onClick={() => setPage(page - 1)}>‹</button>
      {Array.from({ length: totalPages }, (_, i) => i + 1).map((n) => (
        <button key={n} style={btn(n === page)} onClick={() => setPage(n)}>{n}</button>
      ))}
      <button style={btn(false)} disabled={page === totalPages} onClick={() => setPage(page + 1)}>›</button>
    </nav>
  )
}`,
}

function genericTemplate(component: ComponentItem, name: string): string {
  const states = component.states?.length ? `\n * Required states: ${component.states.join(', ')}` : ''
  return `/*
 * Scaffold for "${component.id}" — no dedicated generator yet; the tokens
 * above are exact, adapt the JSX structure to your needs.${states}
 */
export function ${name}() {
  return (
    <div
      style={{
        maxWidth: 420,
        background: T.muted,
        border: \`1px solid \${T.border}\`,
        borderRadius: T.radius,
        boxShadow: T.shadow,
        padding: 20,
        fontFamily: T.font,
      }}
    >
      <h3 style={{ margin: '0 0 8px', color: T.fg, fontSize: 16, fontWeight: 600 }}>${component.title['en-US']}</h3>
      <p style={{ margin: '0 0 14px', color: T.mutedFg, fontSize: 13 }}>${component.description['en-US'].replace(/'/g, '’')}</p>
      <button
        style={{
          padding: '7px 14px',
          background: T.primary,
          color: T.primaryFg,
          border: 'none',
          borderRadius: T.radius,
          fontFamily: T.font,
          fontSize: 13,
          fontWeight: 600,
          cursor: 'pointer',
        }}
      >
        Action
      </button>
    </div>
  )
}`
}

/** IDs that have a dedicated (visually faithful) code template. */
export function hasDedicatedCodeTemplate(componentId: string): boolean {
  return componentId in COMPONENT_TEMPLATES
}

export function componentToReactCode(
  component: ComponentItem,
  tokens: Tokens,
  options?: { styleName?: string; motion?: MotionParams },
): string {
  const t = pickTokens(tokens)
  const name = pascalCase(component.id)
  const template = COMPONENT_TEMPLATES[component.id]
  const body = template ? template(name) : genericTemplate(component, name)

  // Hoist any `import` lines from the template to the top of the file.
  const bodyLines = body.split('\n')
  const importLines = bodyLines.filter((l) => l.startsWith('import '))
  const rest = bodyLines.filter((l) => !l.startsWith('import ')).join('\n').trimStart()

  const parts = [
    `/**
 * ${component.title['en-US']} — generated by Prompt Assistant${options?.styleName ? `\n * Style: ${options.styleName} (tokens baked in below)` : ''}
 * Standalone React component: paste into any React (TS) project.
 */`,
  ]
  if (importLines.length) parts.push(importLines.join('\n'))
  parts.push(tokensConst(t))
  parts.push(rest)
  if (options?.motion) {
    const commented = motionParamsToCode(options.motion)
      .split('\n')
      .slice(1)
      .map((l) => (l ? `// ${l}` : '//'))
      .join('\n')
    parts.push(`// Optional motion layer (npm i motion) — matches the tuned preview:\n${commented}`)
  }
  return parts.join('\n\n')
}

export function styleCodeBundle(style: StyleItem): { css: string; tailwind: string } {
  return {
    css: tokensToCssVars(style.tokens, style.title['en-US']),
    tailwind: tokensToTailwindConfig(style.tokens, style.title['en-US']),
  }
}
