import type { Locale } from '@/types/catalog'

export const previewLabels = {
  confirmDelete: { 'zh-CN': '确认删除', 'en-US': 'Confirm Delete' },
  irreversible: { 'zh-CN': '此操作不可撤销，确定继续吗？', 'en-US': 'This cannot be undone. Continue?' },
  cancel: { 'zh-CN': '取消', 'en-US': 'Cancel' },
  delete: { 'zh-CN': '删除', 'en-US': 'Delete' },
  success: { 'zh-CN': '操作成功', 'en-US': 'Success' },
  saved: { 'zh-CN': '更改已保存。', 'en-US': 'Changes saved.' },
  hint: { 'zh-CN': '提示', 'en-US': 'Notice' },
  updateAvailable: { 'zh-CN': '有新的更新可用。', 'en-US': 'A new update is available.' },
  cardTitle: { 'zh-CN': '卡片标题', 'en-US': 'Card Title' },
  cardDesc: { 'zh-CN': '简短的内容描述文本。', 'en-US': 'Short description text.' },
  view: { 'zh-CN': '查看', 'en-US': 'View' },
  tabOverview: { 'zh-CN': '概览', 'en-US': 'Overview' },
  tabDetails: { 'zh-CN': '详情', 'en-US': 'Details' },
  tabSettings: { 'zh-CN': '设置', 'en-US': 'Settings' },
  tabContent: { 'zh-CN': '「概览」标签页的内容区域。', 'en-US': 'Content for the Overview tab.' },
  accordionExpanded: { 'zh-CN': '展开的内容详情区域。', 'en-US': 'Expanded content details.' },
  faqPrompt: { 'zh-CN': '什么是 Prompt？', 'en-US': 'What is a Prompt?' },
  faqImport: { 'zh-CN': '如何导入风格？', 'en-US': 'How to import styles?' },
  profile: { 'zh-CN': '个人资料', 'en-US': 'Profile' },
  accountSettings: { 'zh-CN': '账户设置', 'en-US': 'Account Settings' },
  signOut: { 'zh-CN': '退出登录', 'en-US': 'Sign Out' },
  tooltipText: { 'zh-CN': '提示文本', 'en-US': 'Tooltip text' },
  hoverMe: { 'zh-CN': '悬停我', 'en-US': 'Hover me' },
  uploading: { 'zh-CN': '上传中', 'en-US': 'Uploading' },
  alertTitle: { 'zh-CN': '提示', 'en-US': 'Notice' },
  alertBody: { 'zh-CN': '这是一条信息提示横幅。', 'en-US': 'This is an inline alert banner.' },
  home: { 'zh-CN': '首页', 'en-US': 'Home' },
  styles: { 'zh-CN': '风格', 'en-US': 'Styles' },
  glassmorphism: { 'zh-CN': '玻璃拟态', 'en-US': 'Glassmorphism' },
  pushNotif: { 'zh-CN': '推送通知', 'en-US': 'Push notifications' },
  darkMode: { 'zh-CN': '深色模式', 'en-US': 'Dark mode' },
  stepAccount: { 'zh-CN': '账户', 'en-US': 'Account' },
  stepProfile: { 'zh-CN': '资料', 'en-US': 'Profile' },
  stepDone: { 'zh-CN': '完成', 'en-US': 'Done' },
  statUsers: { 'zh-CN': '总用户', 'en-US': 'Total users' },
  statRevenue: { 'zh-CN': '收入', 'en-US': 'Revenue' },
  emptyTitle: { 'zh-CN': '暂无数据', 'en-US': 'No data yet' },
  emptyDesc: { 'zh-CN': '点击下方按钮创建第一条记录。', 'en-US': 'Click below to create your first record.' },
  create: { 'zh-CN': '新建', 'en-US': 'Create' },
  day: { 'zh-CN': '日', 'en-US': 'Day' },
  week: { 'zh-CN': '周', 'en-US': 'Week' },
  month: { 'zh-CN': '月', 'en-US': 'Month' },
  searchPlaceholder: { 'zh-CN': '搜索风格、组件...', 'en-US': 'Search styles, components...' },
  username: { 'zh-CN': '用户名', 'en-US': 'Username' },
  usernamePh: { 'zh-CN': '输入用户名', 'en-US': 'Enter username' },
  usernameTaken: { 'zh-CN': '用户名已被占用', 'en-US': 'Username is taken' },
  region: { 'zh-CN': '地区', 'en-US': 'Region' },
  regionCn: { 'zh-CN': '中国大陆', 'en-US': 'Mainland China' },
  marketingEmail: { 'zh-CN': '营销邮件', 'en-US': 'Marketing emails' },
  planStandard: { 'zh-CN': '标准版', 'en-US': 'Standard' },
  planPro: { 'zh-CN': '专业版', 'en-US': 'Pro' },
  description: { 'zh-CN': '描述', 'en-US': 'Description' },
  descriptionPh: { 'zh-CN': '请输入详细描述…', 'en-US': 'Enter a detailed description…' },
  loading: { 'zh-CN': '加载中…', 'en-US': 'Loading…' },
  drawerContent: { 'zh-CN': '抽屉面板内容', 'en-US': 'Drawer panel content' },
  projectAlpha: { 'zh-CN': '项目 Alpha', 'en-US': 'Project Alpha' },
  projectBeta: { 'zh-CN': '项目 Beta', 'en-US': 'Project Beta' },
  updated2h: { 'zh-CN': '2 小时前更新', 'en-US': 'Updated 2h ago' },
  yesterday: { 'zh-CN': '昨天', 'en-US': 'Yesterday' },
  orderCreated: { 'zh-CN': '创建订单', 'en-US': 'Order created' },
  paymentDone: { 'zh-CN': '支付完成', 'en-US': 'Payment completed' },
  shipped: { 'zh-CN': '已发货', 'en-US': 'Shipped' },
  navOverview: { 'zh-CN': '概览', 'en-US': 'Overview' },
  navStyles: { 'zh-CN': '风格', 'en-US': 'Styles' },
  navComponents: { 'zh-CN': '组件', 'en-US': 'Components' },
  commandPh: { 'zh-CN': '输入命令或搜索…', 'en-US': 'Type a command or search…' },
  cmdGoStyles: { 'zh-CN': '跳转：风格库', 'en-US': 'Go: Style library' },
  cmdCopyPrompt: { 'zh-CN': '复制当前 Prompt', 'en-US': 'Copy current Prompt' },
  calendarTitle: { 'zh-CN': '2026 年 6 月', 'en-US': 'June 2026' },
  dropFiles: { 'zh-CN': '拖拽文件到此处', 'en-US': 'Drop files here' },
  fileHint: { 'zh-CN': '或点击选择 · 最大 10MB', 'en-US': 'or click to browse · max 10MB' },
  volume: { 'zh-CN': '音量', 'en-US': 'Volume' },
  moreInfo: { 'zh-CN': '更多信息', 'en-US': 'More info' },
  popoverBody: { 'zh-CN': '弹出层说明文字', 'en-US': 'Popover description text.' },
  copy: { 'zh-CN': '复制', 'en-US': 'Copy' },
  paste: { 'zh-CN': '粘贴', 'en-US': 'Paste' },
  addTag: { 'zh-CN': '添加标签…', 'en-US': 'Add tag…' },
  notifications: { 'zh-CN': '通知', 'en-US': 'Notifications' },
  notifStyleApplied: { 'zh-CN': '风格已应用', 'en-US': 'Style applied' },
  notifPromptCopied: { 'zh-CN': 'Prompt 已复制', 'en-US': 'Prompt copied' },
  ago2m: { 'zh-CN': '2 分钟前', 'en-US': '2 min ago' },
  ago1h: { 'zh-CN': '1 小时前', 'en-US': '1 hour ago' },
} as const

export type PreviewLabelKey = keyof typeof previewLabels

export function pl(key: PreviewLabelKey, locale: Locale): string {
  return previewLabels[key][locale] ?? previewLabels[key]['zh-CN']
}
